homepage: "https://github.com/protocolbuffers/protobuf"
language: c++
primary_contact: "you@example.com"
auto_ccs: []
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
main_repo: "https://github.com/protocolbuffers/protobuf.git"

fuzzing_engines:
  - libfuzzer

